version: '2'

services:
  postgres9:
    image: postgres:latest
    container_name: movies_db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movies_db
    ports:
      - "5432:5432"
    volumes:
      - ~/Docker/movies_db/data:/var/lib/postgresql/data